// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6uL241sw1JWOE-Sy4SPDSaV26rKhbGFs',
    appId: '1:698417262464:web:30dbc93ca3b8425b455b65',
    messagingSenderId: '698417262464',
    projectId: 'yalla-go-603c3',
    authDomain: 'yalla-go-603c3.firebaseapp.com',
    databaseURL: 'https://yalla-go-603c3-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-go-603c3.firebasestorage.app',
    measurementId: 'G-8DTX0QLMTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6XotVjRFnInw9LpzFHNuFZZUDYJTw_CI',
    appId: '1:698417262464:android:e4d85f8d0ceef8e5455b65',
    messagingSenderId: '698417262464',
    projectId: 'yalla-go-603c3',
    databaseURL: 'https://yalla-go-603c3-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-go-603c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjms2eUN-9EkA7JtE0pDJCQ0ZvavFHM2s',
    appId: '1:698417262464:ios:b8392cb971da4291455b65',
    messagingSenderId: '698417262464',
    projectId: 'yalla-go-603c3',
    databaseURL: 'https://yalla-go-603c3-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-go-603c3.firebasestorage.app',
    iosBundleId: 'com.example.yallaGoCaptain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjms2eUN-9EkA7JtE0pDJCQ0ZvavFHM2s',
    appId: '1:698417262464:ios:b8392cb971da4291455b65',
    messagingSenderId: '698417262464',
    projectId: 'yalla-go-603c3',
    databaseURL: 'https://yalla-go-603c3-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-go-603c3.firebasestorage.app',
    iosBundleId: 'com.example.yallaGoCaptain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6uL241sw1JWOE-Sy4SPDSaV26rKhbGFs',
    appId: '1:698417262464:web:f4dfbd99e705d3bf455b65',
    messagingSenderId: '698417262464',
    projectId: 'yalla-go-603c3',
    authDomain: 'yalla-go-603c3.firebaseapp.com',
    databaseURL: 'https://yalla-go-603c3-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-go-603c3.firebasestorage.app',
    measurementId: 'G-9NR71RVX91',
  );
}
